
### post api


### create post

POST http://localhost:3001/api/post
Content-Type: application/json

{
    "sender": "5555",
    "message": "This is a new message"
}


###

### get all posts

GET http://localhost:3001/api/post/all

###

### get posts by id

GET http://localhost:3001/api/post/67320cba1fd0f9c9b52dba0c

###

### get posts by sender

GET http://localhost:3001/api/post?sender=45678

###

### update post

PUT http://localhost:3001/api/post/673211df2b040cf7577abd99
Content-Type: application/json

{
    "message": "This is a new message"
}

###




### comment api


### get comments by post

GET http://localhost:3001/api/comment?post=673211df2b040cf7577abd99

###


### create comment

POST http://localhost:3001/api/comment
Content-Type: application/json

{
    "post": "673211df2b040cf7577abd99",
    "sender": "45678",
    "message": "This is a comment"
}

###